mod atari2600;
mod atari5200;
mod atari7800;
mod colecovision;
mod dreamcast;
mod gamecube;
mod genesis;
mod genesis_vdp;
mod intellivision;
mod jaguar;
mod master_system;
mod neo_geo;
mod nes;
mod nes_apu;
mod nintendo64;
mod odyssey;
mod pc_engine;
mod playstation;
mod playstation2;
mod playstation3;
mod pokey;
mod pong;
mod ps1_cdrom;
mod ps1_gpu;
mod ps1_gte;
mod ps1_mdec;
mod ps1_spu;
mod saturn;
mod sega_32x;
mod sega_cd;
mod sn76489;
mod snes;
mod snes_apu;
mod snes_dsp;
mod snes_dsp1;
mod snes_dsp2;
mod snes_dsp3;
mod snes_ppu;
mod snes_srtc;
mod switch;
mod switch_ipc;
mod three_do;
mod tms9918;
mod wii;
mod wiiu;
mod xbox;
mod xbox360;
mod ym2413;
mod ym2612;

pub use atari2600::Atari2600Machine;
pub use atari5200::Atari5200Machine;
pub use atari7800::Atari7800Machine;
pub use colecovision::ColecoVisionMachine;
pub use dreamcast::DreamcastMachine;
pub use gamecube::GameCubeMachine;
pub use genesis::GenesisMachine;
pub use intellivision::IntellivisionMachine;
pub use jaguar::JaguarMachine;
pub use master_system::MasterSystemMachine;
pub use neo_geo::NeoGeoMachine;
pub use nes::NesMachine;
pub use nintendo64::Nintendo64Machine;
pub use odyssey::OdysseyMachine;
pub use pc_engine::PcEngineMachine;
pub use playstation::PlayStationMachine;
pub use playstation2::PlayStation2Machine;
pub use playstation3::PlayStation3Machine;
pub use pong::PongMachine;
pub use saturn::SaturnMachine;
pub use sega_32x::Sega32xMachine;
pub use sega_cd::SegaCdMachine;
pub use snes::SnesMachine;
pub use switch::SwitchMachine;
pub use three_do::ThreeDoMachine;
pub use wii::WiiMachine;
pub use wiiu::WiiUMachine;
pub use xbox::XboxMachine;
pub use xbox360::Xbox360Machine;
