export type SupportTier = 'playable' | 'foundation' | 'planned'

export interface Platform {
  id: string
  omniCode: number
  name: string
  generation: number
  vendor: string
  years: string
  extensions: string[]
  media?: 'cartridge' | 'disc' | 'package'
  discExtensions?: string[]
  tier: SupportTier
  bios?: 'optional' | 'required'
  discBios?: 'optional' | 'required'
  firmware?: 'optional' | 'required'
  romless?: boolean
  launchable?: boolean
  note?: string
}

const p = (platform: Platform) => platform

export const PLATFORMS: Platform[] = [
  p({ id: 'odyssey', omniCode: 1, name: 'Magnavox Odyssey', generation: 1, vendor: 'Magnavox', years: '1972–1975', extensions: [], tier: 'playable', romless: true, launchable: true, note: 'Dedicated silent discrete-logic graph with two independently positioned player spots, ball/reset/English behavior, center/speed controls, wall/gate behavior, and the six base game-card wiring configurations; no ROM is required.' }),
  p({ id: 'home-pong', omniCode: 2, name: 'Home Pong / Telstar class', generation: 1, vendor: 'Atari / Coleco', years: '1975–1978', extensions: [], tier: 'playable', romless: true, launchable: true, note: 'Built directly into the single OmniCore binary; no ROM is required.' }),
  p({ id: 'atari2600', omniCode: 10, name: 'Atari 2600', generation: 2, vendor: 'Atari', years: '1977–1992', extensions: ['a26', 'bin'], tier: 'foundation', launchable: true, note: 'Launchable development graph: 6507-style 13-bit bus using the shared 6502, RIOT RAM/I/O/timer, TIA playfield/players/missiles/ball/collisions/audio, WSYNC timing, controllers, and 2K/4K, F8/F6/F4, SuperChip, E0, E7, 3F, FE, UA, F0 and FA cartridge hardware with deterministic cartridge state. Exact TIA timing, specialty/modern bankswitch hardware and peripheral breadth remain.' }),
  p({ id: 'atari5200', omniCode: 11, name: 'Atari 5200', generation: 2, vendor: 'Atari', years: '1982–1984', extensions: ['a52', 'bin'], tier: 'foundation', bios: 'required', launchable: true, note: 'Launchable development graph: shared NMOS 6502, ANTIC display-list foundation, GTIA color/trigger registers, POKEY analog inputs/audio/IRQ, 16 KiB RAM and cartridge/BIOS map. ANTIC/GTIA timing and mode coverage remain incomplete.' }),
  p({ id: 'coleco', omniCode: 12, name: 'ColecoVision', generation: 2, vendor: 'Coleco', years: '1982–1985', extensions: ['col', 'rom', 'bin'], tier: 'foundation', launchable: true, bios: 'required', note: 'Launchable development graph: shared Z80 and SN76489, required user BIOS, TMS9918 Graphics I/II tile and sprite rendering, VDP NMI, controllers, audio and deterministic save states. Keypad completeness, timing and compatibility validation remain.' }),
  p({ id: 'intellivision', omniCode: 13, name: 'Intellivision', generation: 2, vendor: 'Mattel', years: '1979–1990', extensions: ['int', 'bin', 'rom'], tier: 'foundation', bios: 'required', firmware: 'required', launchable: true, note: 'Launchable development graph: CP1610 execution, EXEC/GROM firmware loading, STIC background-card and MOB rendering, AY-3-8914 tone/noise/envelope generation, active-low disc/action/keypad controls, Intellicart segmented images, and deterministic save states. Broad cartridge-format coverage and hardware timing validation remain.' }),
  p({ id: 'nes', omniCode: 20, name: 'NES / Famicom', generation: 3, vendor: 'Nintendo', years: '1983–2003', extensions: ['nes'], tier: 'foundation', launchable: true, note: 'Launchable development graph: shared 6502 CPU, CPU/PPU buses, controllers, OAM/DMC DMA, dot-timed PPU rendering, APU audio, deterministic state/persistence, NES 2.0 sizing, and mapper 0/1/2/3/4/5/7/9/10/11/13/16/18/19/21/22/23/24/25/26/32/33/34/64/66/69/71/73/75/76/79/85/87/88/94/95/113/118/140/146/154/155/158/180/184/206/210/232/241 support. Exact PPU/APU edge timing, PAL/Dendy behavior, additional boards/expansion audio and broad compatibility validation remain.' }),
  p({ id: 'segaMS', omniCode: 21, name: 'Sega Master System', generation: 3, vendor: 'Sega', years: '1985–1996', extensions: ['sms'], tier: 'foundation', launchable: true, bios: 'optional', note: 'Launchable development graph: reusable Z80, Sega mapper/SRAM, Mode 4 VDP background/sprites, frame/line interrupts, scroll locks, controllers, SN76489 audio and save states. Timing, legacy VDP modes, uncommon mappers and compatibility validation remain.' }),
  p({ id: 'atari7800', omniCode: 22, name: 'Atari 7800', generation: 3, vendor: 'Atari', years: '1986–1992', extensions: ['a78', 'bin'], tier: 'foundation', launchable: true, note: 'Launchable development graph: shared NMOS 6502/SALLY execution, console RAM/PIA/TIA audio/input, MARIA DLL/display-list rendering foundation, linear and SuperGame cartridges, optional POKEY mappings, and deterministic save states. MARIA DMA timing/modes and mapper breadth remain incomplete.' }),
  p({ id: 'snes', omniCode: 30, name: 'SNES / Super Famicom', generation: 4, vendor: 'Nintendo', years: '1990–2003', extensions: ['sfc', 'smc', 'fig', 'swc'], tier: 'foundation', launchable: true, bios: 'optional', note: 'Launchable development graph: reusable W65C816, LoROM/HiROM mapping, WRAM and CPU I/O, serial controllers, NMI/vblank timing, VRAM/CGRAM/OAM PPU register foundation, Mode 0/1 BG1 rendering, SRAM persistence and deterministic state. General DMA/HDMA and integrated SPC700 S-SMP RAM/ports/timers with firmware-free IPL transfer HLE are implemented; BRR-based eight-voice S-DSP audio is now wired to the browser; Gaussian interpolation/echo/FIR/exact DSP timing, full PPU modes/sprites and enhancement chips remain.' }),
  p({ id: 'segaMD', omniCode: 31, name: 'Genesis / Mega Drive', generation: 4, vendor: 'Sega', years: '1988–1997', extensions: ['md', 'gen', 'smd', 'bin'], tier: 'foundation', launchable: true, note: 'Launchable development graph: shared Motorola 68000 and Z80 execution, Genesis memory/I/O and bus-request/reset paths, VRAM/CRAM/VSRAM VDP foundation with planes/sprites/interrupts, YM2612 register/timer/FM/DAC foundation, SN76489 PSG, controllers, SRAM persistence, SMD decoding, and the official Super Street Fighter II 512 KiB bank mapper. Cycle-exact VDP/DMA, full FM accuracy and broad cartridge compatibility remain.' }),
  p({ id: 'segaCD', omniCode: 32, name: 'Sega CD / Mega-CD', generation: 4, vendor: 'Sega', years: '1991–1996', extensions: ['iso', 'bin'], media: 'disc', tier: 'foundation', bios: 'required', launchable: true, note: 'Launchable disc-development graph extending the Genesis hardware path with a second 68000, 512 KiB PRG RAM, 256 KiB shared Word RAM with ownership/mode switching, 8 KiB backup RAM, gate-array communication/timer/IRQ state, 75 Hz streamed ISO/raw-sector access, and RF5C164-compatible eight-channel PCM foundation. CUE/CHD parsing, full CDC/CDD command behavior, stamp-map graphics, exact bus arbitration/timing and broad compatibility validation remain.' }),
  p({ id: 'sega32x', omniCode: 33, name: 'Sega 32X', generation: 4, vendor: 'Sega', years: '1994–1996', extensions: ['32x', 'bin'], tier: 'foundation', launchable: true, note: 'Launchable MARS development graph extending the Genesis hardware path with dual big-endian SH-2 execution, 256 KiB SDRAM, 2 x 128 KiB frame buffers, packed/direct/RLE bitmap composition and priority, communication/interrupt registers, ROM banking, hardware fill/overwrite behavior, and PWM audio foundation. Proprietary adapter boot ROM behavior is HLEd from the cartridge MARS header; SH-2 on-chip peripherals, exact arbitration/timing, DMA, PWM timing and broad compatibility validation remain.' }),
  p({ id: 'pce', omniCode: 34, name: 'TurboGrafx-16 / PC Engine', generation: 4, vendor: 'NEC', years: '1987–1994', extensions: ['pce', 'cue', 'iso', 'bin'], discExtensions: ['cue', 'iso', 'bin'], discBios: 'required', tier: 'foundation', launchable: true, note: 'Launchable HuCard and CD-ROM development graph: HuC6280 MPR/timer/IRQ/speed and major extension opcodes, HuC6270 VRAM/BAT/sprite/DMA/raster foundation, HuC6260 512-color palette, six-channel PSG with waveform/DDA/noise, two-button joypad mux plus Street Fighter II six-button scanning, standard HuCards plus Street Fighter II bank switching and canonical Populous cartridge RAM, System Card 3 memory/register mapping, Arcade Card 2 MiB DRAM with four programmable access ports plus shift/rotate registers, SCSI READ(6) sector transport with IRQ2, streamed ISO/raw-2352 media, multitrack CUE with BINARY/WAVE sources, track-aware directory/SubQ responses, CD-DA playback mixed into the public 48 kHz output, CD backup RAM persistence, MSM5205-compatible ADPCM decode/playback with programmable rate, CPU-port pipeline delays, CD-to-ADPCM DMA, full-play IRQ, CD-DA/ADPCM fader commands, and deterministic state. Hardware-validated ADPCM/fader timing, exact CD-DA/SCSI timing, CHD media, broader System Card variants, remaining specialty HuCard/accessory profiles, exact VDC timing and broad compatibility validation remain.' }),
  p({ id: 'supergrafx', omniCode: 36, name: 'PC Engine SuperGrafx', generation: 4, vendor: 'NEC', years: '1989–1991', extensions: ['sgx', 'pce'], tier: 'foundation', launchable: true, note: 'Launchable SuperGrafx development graph: shared HuC6280 and PSG foundation with two independent HuC6270 VDCs, HuC6202 VPC register/window priority control, ST-port-selected VDC access, combined video IRQ routing, deterministic dual-VDC composition, and save states. Exact VDC/VPC dot timing, SuperGrafx CD expansion behavior, remaining specialty cartridge/accessory profiles and broad compatibility validation remain.' }),
  p({ id: 'neo-geo', omniCode: 35, name: 'Neo Geo', generation: 4, vendor: 'SNK', years: '1990–2004', extensions: ['neo'], tier: 'foundation', bios: 'required', launchable: true, note: 'Launchable NEO1 cartridge development graph: shared Motorola 68000 and Z80 execution, BIOS/cartridge vector switching, work/backup/card memory, VRAM and dual palette banks, FIX/sprite rendering foundation, vblank/timer IRQs, sound-command NMI path, and YM2610 SSG/timer plus ADPCM-A/B sample-playback foundations. FM accuracy, protected/banked cartridge hardware, raw ZIP set assembly, exact raster timing and broad compatibility validation remain.' }),
  p({ id: 'psx', omniCode: 40, name: 'PlayStation', generation: 5, vendor: 'Sony', years: '1994–2006', extensions: ['cue', 'bin', 'img', 'iso'], media: 'disc', tier: 'foundation', launchable: true, bios: 'required', note: 'Launchable development graph: MIPS R3000A CPU, 2 MiB RAM/scratchpad/BIOS map and COP0 IRQ path, BIOS memory-control/I-cache/cache-isolation behavior and native partial-MMIO store semantics; COP2/GTE with delayed register writes, CPU/GTE overlap, hardware-measured input-latch timing for perspective/clipping/depth and non-aliasing lighting inputs, RTPS/RTPT projection, NCLIP/AVSZ, MVMVA/vector math, lighting/color/depth-cue commands, UNR division and FLAG saturation behavior; GPU flat/Gouraud polygons, fixed-point line/polylines, 12-bit-quantized polygon color/UV gradients, 480i active-field drawing/GPUSTAT parity, measured GP0 command busy/readiness timing, sprites, 4/8/15-bit textures, CLUTs, texture windows, modulation, semi-transparency, draw area/offset, mask rules, VRAM transfers, programmable PAL/NTSC/interlaced/24-bit scanout, DPCR-priority/gated MDEC/GPU/CD-ROM/SPU/OTC DMA with DICR IRQs, BFRD gating, RAM_SIZE windows and bus errors; three root counters with system/dot/HBlank/divide-by-eight clocks and target/overflow IRQs; two-port SIO0 with digital-pad compatibility, DualShock-class analog/config commands, four stick axes, L3/R3 and rumble mapping state; a formatted 128 KiB memory card with in-game read/write/ID/checksum protocol plus host persistence; and streamed CD sectors with queued command/interrupt handshakes plus staged MotorOn/Stop/Pause/Init/SetSession/Seek/GetID/GetQ/ReadTOC completion; an MDEC path with command/status MMIO, quant/scale tables, RLE/IDCT macroblock decode and DMA0/DMA1; and a 24-voice SPU with SPU-ADPCM, Gaussian interpolation, ADSR, pitch/noise, fixed/swept stereo volume, reverb RAM/register processing, sound-RAM DMA, IRQ9 and deterministic stereo output. Raw-sector CD-DA Play/Mute/Demute and XA-ADPCM Mode 2 audio are live with file/channel filtering, 4/8-bit decode, 18.9/37.8 kHz handling, zig-zag resampling, ADPMUTE, the controller ATV volume matrix and SPU CD-input routing. Multitrack CUE loading supports BINARY data/audio tracks, 44.1 kHz PCM WAVE tracks, INDEX/PREGAP/POSTGAP layout, TOC/subchannel position reporting and AutoPause while remaining demand-paged; same-basename SBI companions preserve the LibCrypt bad-Q retained-SubQ behavior. Aliasing/multi-read GTE latch edges, exact reverb edge timing, CHD/PBP and full raw-subchannel media support, full asynchronous GPU FIFO/command arbitration, sub-scanline MDEC/timer timing and broad compatibility validation remain.' }),
  p({ id: 'n64', omniCode: 41, name: 'Nintendo 64', generation: 5, vendor: 'Nintendo', years: '1996–2002', extensions: ['n64', 'z64', 'v64'], tier: 'foundation', launchable: true, note: 'Launchable cartridge-development graph: reusable 64-bit R4300-class CPU with COP0/TLB/LL-SC, big-endian memory, and COP1 register/control state with 32/64-bit moves and loads/stores, S/D arithmetic, comparisons/branches and integer conversions; reusable scalar/vector RSP foundation; HLE PIF boot into cartridge IPL3; 8 MiB RDRAM; SP/DP/MI/VI/AI/PI/SI register and DMA foundations; Joybus controller/Controller Pak paths; RDP color-image/fill-rectangle foundation; SRAM-style persistence; and deterministic state. Bit-exact FPU exception/subnormal behavior, exact RSP reciprocal/vector edge behavior, complete RDP rasterization, CIC/PIF variants, EEPROM/Flash save protocols, timing/arbitration and broad compatibility validation remain.' }),
  p({ id: 'segaSaturn', omniCode: 42, name: 'Sega Saturn', generation: 5, vendor: 'Sega', years: '1994–2000', extensions: ['iso', 'bin'], media: 'disc', tier: 'foundation', launchable: true, bios: 'required', note: 'Launchable development graph: dual shared SH-2 execution, 512 KiB BIOS, 1 MiB low and high work RAM, SMPC processor/input foundation, SCU interrupt and three-channel DMA foundation, VDP1 command/framebuffer rendering into a VDP2 display compositor, 32-slot SCSP PCM foundation with sound-68000 bus, backup RAM persistence, streamed ISO/raw-sector CD access, and deterministic state. Full VDP1/VDP2 modes, SCSP DSP/FM fidelity, SH-2 on-chip peripherals, exact SCU/SMPC timing, complete CD Block commands, CUE/CHD/multitrack media and broad compatibility validation remain.' }),
  p({ id: 'jaguar', omniCode: 43, name: 'Atari Jaguar', generation: 5, vendor: 'Atari', years: '1993–1996', extensions: ['j64', 'jag', 'rom', 'bin'], tier: 'foundation', bios: 'required', launchable: true, note: 'Launchable cartridge-development graph: shared Motorola 68000, reusable Tom/Jerry RISC execution for GPU and DSP, 2 MiB DRAM with ROMHI boot overlay, 6 MiB cartridge window, 128 KiB user BIOS, Tom register/CLUT/line-buffer foundation with bitmap/scaled-bitmap object rendering, active-low keypad/controller matrix, Jerry stereo DAC path, cartridge EEPROM persistence, and deterministic state. Full object-processor branch/update semantics, blitter, RISC interrupt pipelines, Jerry timers/serial audio, exact bus arbitration/timing, Jaguar CD, and broad compatibility validation remain.' }),
  p({ id: '3do', omniCode: 44, name: '3DO', generation: 5, vendor: '3DO', years: '1993–1996', extensions: ['iso', 'bin'], media: 'disc', tier: 'foundation', launchable: true, bios: 'required', note: 'Launchable development graph: reusable ARM60/ARMv3 execution, 2 MiB DRAM, dual-ported VRAM window, 1 MiB BIOS boot overlay/high bank, 32 KiB NVRAM persistence, MADAM register/CEL foundation, CLIO controller/FIQ foundation, 16-voice DSPP PCM foundation, SPORT aliasing, streamed ISO/raw-sector XBus CD access, and deterministic state. Full CEL/VDLP behavior, programmable DSPP, exact MADAM/CLIO timing, complete XBus/CD commands, CUE/CHD/multitrack media and broad compatibility validation remain.' }),
  p({ id: 'dreamcast', omniCode: 50, name: 'Dreamcast', generation: 6, vendor: 'Sega', years: '1998–2001', extensions: ['iso', 'bin'], media: 'disc', tier: 'foundation', launchable: true, bios: 'required', note: 'Launchable development graph: dedicated little-endian SH-4 execution with banked privileged state and FPU foundations, ARM7TDMI/Thumb AICA CPU execution, 16 MiB main RAM, 8 MiB PowerVR VRAM, 2 MiB sound RAM, HOLLY interrupt routing, framebuffer scanout, Maple controller DMA, AICA PCM, 128 KiB flash persistence, streamed ISO/raw-sector GD-ROM access, and deterministic state. Complete PowerVR2 tile/raster behavior, AICA DSP/ADPCM fidelity, GD-ROM command/media breadth, SH-4 MMU/cache/peripherals, exact timing, and broad compatibility validation remain.' }),
  p({ id: 'ps2', omniCode: 51, name: 'PlayStation 2', generation: 6, vendor: 'Sony', years: '2000–2013', extensions: ['elf', 'iso'], media: 'disc', tier: 'foundation', launchable: true, bios: 'optional', note: 'Launchable HLE development graph: reusable 128-bit R5900/Emotion Engine execution with MMI foundations, 32 MiB EE RAM, 16 KiB scratchpad, optional 4 MiB BIOS mapping, ELF32/MIPS loading, ISO9660 SYSTEM.CNF/BOOT2 discovery, INTC and timer foundations, GIF packed A+D and image-transfer parsing, GIF DMAC channel-2 normal/source-chain transfers with DMAtag CALL/RET/TIE handling and D_STAT interrupts, 4 MiB GS VRAM with PSMCT32 framebuffer scanout, 8 MiB memory-card persistence, and deterministic state. Full BIOS boot, IOP/SIF/SIO2 controllers, VU0/VU1 execution, complete GIF/GS raster and swizzle behavior, remaining DMAC channels and timing/stalls, CDVD breadth, SPU2 audio, exact timing, CHD, and broad compatibility validation remain.' }),
  p({ id: 'gamecube', omniCode: 52, name: 'Nintendo GameCube', generation: 6, vendor: 'Nintendo', years: '2001–2007', extensions: ['dol', 'iso', 'gcm'], media: 'disc', tier: 'foundation', launchable: true, bios: 'optional', note: 'Launchable development graph: reusable PowerPC 750/Gekko execution with paired-single arithmetic, comparisons, merges, quantized PSQ loads/stores, GQR0-7 and HID2 controls, hardware-table fres/frsqrte and paired estimate behavior, full-width single-precision operands, 25-bit frC multiply/FMA handling, fused scalar/paired FMA rounding, FPSCR rounding/NI behavior, disabled single-precision overflow/underflow/inexact status with FI/FR/XX, FPRF/FPCC classification, NaN-aware compares, invalid arithmetic flags, and correct opcode-63 A-form decode; 24 MiB MEM1; 16 MiB ARAM; Flipper PI/DI/SI/VI/DSP register foundations; direct DOL and raw-disc bootstrap; HLE BS2 Disc-ID/DTK reconstruction plus streamed DVD DMA with Disc-ID gating, Request Error, seek/stop-motor, DTK configuration/status state, demand-paged 48 kHz stereo DTK ADPCM decoding/mixing and block-timed stream position; four GameCube controllers; YUYV XFB scanout; 48 kHz audio DMA; channel-0/channel-1 EXI transfer and interrupt handling with independent Slot A/Slot B memory-card persistence; channel-2 AD16 ID/read/write trace-register transfers; optional user-supplied 2 MiB IPL ROM access with raw-dump descrambling and font reads; IPL UART/eUART debug-register handling; channel-0 chip-select-2 IPL SRAM read/write/DMA with deterministic RTC; and deterministic state. Remaining work includes Gekko enabled overflow/underflow/inexact exception-result delivery, paired-single rounding-flag aggregation, pathological subnormal/FMA exponent cases, full GX/Flipper graphics, DSP microcode, additional EXI devices, sub-frame DTK/drive scheduling, exact timing, RVZ/CHD containers, and broad compatibility validation.' }),
  p({ id: 'xbox', omniCode: 53, name: 'Xbox', generation: 6, vendor: 'Microsoft', years: '2001–2009', extensions: ['xbe'], tier: 'foundation', launchable: true, note: 'Launchable XBE-development graph: reusable 32-bit x86/Pentium-class execution with ModR/M+SIB addressing, integer/control/stack/string foundations, CPUID/RDTSC and deterministic state; 64 MiB shared RAM with retail shadow aliases; XBE header/section loading with retail/debug entry decoding; NV2A, MCPX APU and AC97 register apertures; PCRTC framebuffer scanout; and deterministic machine state. This does not yet claim retail game compatibility: kernel thunk HLE or BIOS/MCPX boot, NV2A PGRAPH/PFIFO rendering, USB controllers, APU/AC97 audio, IDE/DVD/FATX, networking, exact chipset timing, XISO media and broad validation remain.' }),
  p({ id: 'xbox360', omniCode: 60, name: 'Xbox 360', generation: 7, vendor: 'Microsoft', years: '2005–2016', extensions: ['elf'], tier: 'foundation', launchable: true, note: 'Launchable homebrew-development graph: reusable big-endian 64-bit PowerPC execution, three Xenon core objects, 512 MiB unified guest memory backed by sparse host pages, bounded ELF64/PowerPC segment loading, unified video/audio surfaces, and deterministic CPU/memory state. Retail Xbox 360 compatibility is not claimed: SMT second hardware threads, VMX128, MMU/cache/interrupt fidelity, XEX/hypervisor/kernel boot, Xenos GPU/eDRAM, Southbridge, audio, storage/optical media, controllers, networking, exact timing and broad validation remain.' }),
  p({ id: 'ps3', omniCode: 61, name: 'PlayStation 3', generation: 7, vendor: 'Sony', years: '2006–2017', extensions: ['elf'], tier: 'foundation', launchable: true, note: 'Launchable homebrew-development graph: reusable big-endian 64-bit PowerPC PPE execution, 256 MiB XDR and 256 MiB RSX guest memory backed by sparse host pages, seven 256 KiB visible SPU local-store regions, bounded ELF64/PowerPC loading, unified video/audio surfaces, and deterministic PPE/XDR/RSX/SPU-local-store state. Retail PS3 compatibility is not claimed: PPE second thread and VMX depth, SPU execution/MFC/EIB, MMU/cache/interrupt fidelity, SELF/LV0/LV1/LV2 boot, RSX FIFO/raster/shaders, storage/optical media, controllers, audio, networking, exact timing and broad validation remain.' }),
  p({ id: 'wii', omniCode: 62, name: 'Nintendo Wii', generation: 7, vendor: 'Nintendo', years: '2006–2013', extensions: ['dol'], tier: 'foundation', launchable: true, note: 'Launchable homebrew-development graph: Broadway-compatible PowerPC/Gekko execution, 24 MiB MEM1 plus 64 MiB MEM2 and cached/uncached aliases, Flipper register window, documented Hollywood PPC IPC registers and interrupt boundary, Wii low-memory clock/MEM2 fields, YUYV XFB scanout, fixed-rate audio surface, and deterministic state. This does not yet claim retail Wii software: IOS/Starlet ARM execution and services, encrypted disc/WBFS/RVZ loading and keys, NAND/ES/DI/USB/Bluetooth, Wii Remote support, complete Hollywood/GX/DSP behavior, exact timing, persistence, and broad compatibility validation remain.' }),
  p({ id: 'wiiu', omniCode: 70, name: 'Wii U', generation: 8, vendor: 'Nintendo', years: '2012–2017', extensions: ['elf'], tier: 'foundation', launchable: true, note: 'Launchable homebrew-development graph: three Espresso PowerPC core objects reusing the 750-class execution substrate, 32 MiB MEM1 plus 2 GiB MEM2 represented with sparse backing and explicit guest-address translation, bounded big-endian ELF32/PowerPC loading, unified video/audio surfaces, and deterministic CPU/memory state. Retail Wii U compatibility is not claimed: secondary-core release/SMP fidelity, Cafe OS/RPX/RPL linking, Starbuck/IOSU, Latte/GX2, DSP/audio, GamePad/controllers, storage/optical media, networking, MMU/cache/interrupt timing and broad validation remain.' }),
  p({ id: 'switch', omniCode: 71, name: 'Nintendo Switch', generation: 8, vendor: 'Nintendo', years: '2017–', extensions: ['nro'], tier: 'foundation', launchable: true, note: 'Launchable homebrew-development graph: reusable little-endian AArch64 execution, four application-core state objects, 4 GiB guest DRAM with sparse host backing, validated NRO0 text/rodata/data segment loading and BSS handling, homebrew ABI entry registers, bounded execution, unified video/audio surfaces, and deterministic CPU/memory state. Retail Switch compatibility is not claimed: Horizon services, NSO/NCA/NPDM loading, NSP/XCI containers, user-owned keys/firmware, Maxwell GPU/NVN, audio, controllers, storage, networking, MMU/cache/interrupt timing, multicore scheduling, and broad validation remain. OmniEmu does not distribute console keys or firmware.' }),
]

export const READY_PLATFORMS = PLATFORMS.filter((platform) => platform.tier === 'playable')
export const platformById = (id: string) => PLATFORMS.find((platform) => platform.id === id)
export const corePlayable = (platform: Platform) => platform.tier === 'playable'

const extensionForFile = (name: string | null | undefined) => name?.split('.').pop()?.toLowerCase() ?? ''

export const mediaForFile = (platform: Platform, name: string | null | undefined) => {
  const extension = extensionForFile(name)
  if (platform.discExtensions?.includes(extension)) return 'disc' as const
  return platform.media ?? 'cartridge'
}

export const biosForFile = (platform: Platform, name: string | null | undefined) => {
  if (mediaForFile(platform, name) === 'disc' && platform.discBios) return platform.discBios
  return platform.bios
}

export const candidatesForFile = (name: string) => {
  const extension = extensionForFile(name)
  return PLATFORMS.filter((platform) => platform.extensions.includes(extension))
}
